package DataDictionaryDsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class quick_fix_remove_empty_structure_QuickFix extends QuickFix_Runtime {
  public quick_fix_remove_empty_structure_QuickFix() {
    super(new SNodePointer("r:98240634-8132-4253-b351-9c7ee2a54fa8(DataDictionaryDsl.typesystem)", "2020121436169542405"));
  }
  public String getDescription(SNode node) {
    return "Remove empty structure.";
  }
  public void execute(SNode node) {
    if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(((SNode) quick_fix_remove_empty_structure_QuickFix.this.getField("structure")[0])), MetaAdapterFactory.getConcept(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff46L, "DataDictionaryDsl.structure.StructureDefinition"))) {
      SNodeOperations.deleteNode(SNodeOperations.getParent(((SNode) quick_fix_remove_empty_structure_QuickFix.this.getField("structure")[0])));
    } else {
      SNodeOperations.deleteNode(((SNode) quick_fix_remove_empty_structure_QuickFix.this.getField("structure")[0]));
    }
  }
}
