package DataDictionaryDsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class quick_fix_remove_field_definition_QuickFix extends QuickFix_Runtime {
  public quick_fix_remove_field_definition_QuickFix() {
    super(new SNodePointer("r:98240634-8132-4253-b351-9c7ee2a54fa8(DataDictionaryDsl.typesystem)", "2020121436168446828"));
  }
  public String getDescription(SNode node) {
    return "Remove bad domain.";
  }
  public void execute(SNode node) {
    SNodeOperations.deleteNode(((SNode) quick_fix_remove_field_definition_QuickFix.this.getField("fieldDef")[0]));
  }
}
