package DataDictionaryDsl.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Arrays;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "DataDictionaryDsl";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (Arrays.binarySearch(stringSwitchCases_tpto26_a0a0a0c, concept.getName())) {
        case 0:
          return Collections.<NodeFactory>singletonList(new char_factory.NodeFactory_2020121436165931317());
        case 1:
          return Collections.<NodeFactory>singletonList(new field_factory.NodeFactory_8815957381151922624());
        case 2:
          return Collections.<NodeFactory>singletonList(new integer_factory.NodeFactory_2020121436166587902());
        case 3:
          return Collections.<NodeFactory>singletonList(new node_factories_StructureDefinition.NodeFactory_510907218762934095());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

  private static String[] stringSwitchCases_tpto26_a0a0a0c = new String[]{"Char", "Field", "Integer", "StructureDefinition"};
}
