package DataDictionaryDsl.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import DataDictionaryDsl.behavior.IAbstractElement__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import DataDictionaryDsl.behavior.DataDictionary__BehaviorDescriptor;

public class field_factory {
  public static class NodeFactory_8815957381151922624 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      SNode root = IAbstractElement__BehaviorDescriptor.getRootElement_id7Do$CtUwF3V.invoke(((SNode) enclosingNode));
      SPropertyOperations.assign(newNode, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Field-" + ((int) DataDictionary__BehaviorDescriptor.getFieldsNumber_id7Do$CtUxzUJ.invoke(root) + 1));
    }
  }
}
