package DataDictionaryDsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Aggregation = 0;
  public static final int Boolean = 1;
  public static final int Char = 2;
  public static final int DataDictionary = 3;
  public static final int DateTime = 4;
  public static final int Domain = 5;
  public static final int Exclusive = 6;
  public static final int Field = 7;
  public static final int FieldDefinition = 8;
  public static final int IAbstractElement = 9;
  public static final int IAbstractStructure = 10;
  public static final int ISpecialization = 11;
  public static final int Integer = 12;
  public static final int NonExclusive = 13;
  public static final int Predefined = 14;
  public static final int Semantic = 15;
  public static final int Set = 16;
  public static final int StructureDefinition = 17;
  public static final int Text = 18;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x16d63821a9174aafL, 0xa85f305cd4a0013fL);
    builder.put(0x73ede05be9c14454L, Aggregation);
    builder.put(0x1c08e9be3de0a121L, Boolean);
    builder.put(0x1c08e9be3db505a7L, Char);
    builder.put(0x73ede05be9bfff49L, DataDictionary);
    builder.put(0x1c08e9be3dd493f3L, DateTime);
    builder.put(0xd45dfaeceabe780L, Domain);
    builder.put(0x7171b68977873f0L, Exclusive);
    builder.put(0x73ede05be9c14433L, Field);
    builder.put(0x1c08e9be3d6d982aL, FieldDefinition);
    builder.put(0x7171b68977873e6L, IAbstractElement);
    builder.put(0x7171b68977873e5L, IAbstractStructure);
    builder.put(0x7171b68977873efL, ISpecialization);
    builder.put(0x1c08e9be3dd68bbcL, Integer);
    builder.put(0x73ede05be9c1bfe4L, NonExclusive);
    builder.put(0xd45dfaeceabe939L, Predefined);
    builder.put(0x1cba01accce91399L, Semantic);
    builder.put(0x73ede05be9c14455L, Set);
    builder.put(0x73ede05be9bfff46L, StructureDefinition);
    builder.put(0x1c08e9be3de4c133L, Text);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
