package DataDictionaryDsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAggregation = createDescriptorForAggregation();
  /*package*/ final ConceptDescriptor myConceptBoolean = createDescriptorForBoolean();
  /*package*/ final ConceptDescriptor myConceptChar = createDescriptorForChar();
  /*package*/ final ConceptDescriptor myConceptDataDictionary = createDescriptorForDataDictionary();
  /*package*/ final ConceptDescriptor myConceptDateTime = createDescriptorForDateTime();
  /*package*/ final ConceptDescriptor myConceptDomain = createDescriptorForDomain();
  /*package*/ final ConceptDescriptor myConceptExclusive = createDescriptorForExclusive();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptFieldDefinition = createDescriptorForFieldDefinition();
  /*package*/ final ConceptDescriptor myConceptIAbstractElement = createDescriptorForIAbstractElement();
  /*package*/ final ConceptDescriptor myConceptIAbstractStructure = createDescriptorForIAbstractStructure();
  /*package*/ final ConceptDescriptor myConceptISpecialization = createDescriptorForISpecialization();
  /*package*/ final ConceptDescriptor myConceptInteger = createDescriptorForInteger();
  /*package*/ final ConceptDescriptor myConceptNonExclusive = createDescriptorForNonExclusive();
  /*package*/ final ConceptDescriptor myConceptPredefined = createDescriptorForPredefined();
  /*package*/ final ConceptDescriptor myConceptSemantic = createDescriptorForSemantic();
  /*package*/ final ConceptDescriptor myConceptSet = createDescriptorForSet();
  /*package*/ final ConceptDescriptor myConceptStructureDefinition = createDescriptorForStructureDefinition();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAggregation, myConceptBoolean, myConceptChar, myConceptDataDictionary, myConceptDateTime, myConceptDomain, myConceptExclusive, myConceptField, myConceptFieldDefinition, myConceptIAbstractElement, myConceptIAbstractStructure, myConceptISpecialization, myConceptInteger, myConceptNonExclusive, myConceptPredefined, myConceptSemantic, myConceptSet, myConceptStructureDefinition, myConceptText);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Aggregation:
        return myConceptAggregation;
      case LanguageConceptSwitch.Boolean:
        return myConceptBoolean;
      case LanguageConceptSwitch.Char:
        return myConceptChar;
      case LanguageConceptSwitch.DataDictionary:
        return myConceptDataDictionary;
      case LanguageConceptSwitch.DateTime:
        return myConceptDateTime;
      case LanguageConceptSwitch.Domain:
        return myConceptDomain;
      case LanguageConceptSwitch.Exclusive:
        return myConceptExclusive;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.FieldDefinition:
        return myConceptFieldDefinition;
      case LanguageConceptSwitch.IAbstractElement:
        return myConceptIAbstractElement;
      case LanguageConceptSwitch.IAbstractStructure:
        return myConceptIAbstractStructure;
      case LanguageConceptSwitch.ISpecialization:
        return myConceptISpecialization;
      case LanguageConceptSwitch.Integer:
        return myConceptInteger;
      case LanguageConceptSwitch.NonExclusive:
        return myConceptNonExclusive;
      case LanguageConceptSwitch.Predefined:
        return myConceptPredefined;
      case LanguageConceptSwitch.Semantic:
        return myConceptSemantic;
      case LanguageConceptSwitch.Set:
        return myConceptSet;
      case LanguageConceptSwitch.StructureDefinition:
        return myConceptStructureDefinition;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAggregation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Aggregation", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14454L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210541140");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Boolean", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3de0a121L);
    b.class_(false, false, false);
    b.super_("DataDictionaryDsl.structure.Predefined", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2020121436166856993");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForChar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Char", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3db505a7L);
    b.class_(false, false, false);
    b.super_("DataDictionaryDsl.structure.Predefined", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2020121436163999143");
    b.version(2);
    b.property("length", 0x1c08e9be3db505a8L).type(PrimitiveTypeId.INTEGER).origin("2020121436163999144").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataDictionary() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "DataDictionary", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff49L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210457929");
    b.version(2);
    b.aggregate("structures", 0x73ede05be9bfff4cL).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff46L).optional(true).ordered(true).multiple(true).origin("8353579569210457932").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDateTime() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "DateTime", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3dd493f3L);
    b.class_(false, false, false);
    b.super_("DataDictionaryDsl.structure.Predefined", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2020121436166067187");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomain() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Domain", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe780L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/956416437770774400");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExclusive() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Exclusive", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873f0L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873efL);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642992");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Field", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14433L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210541107");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldDefinition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "FieldDefinition", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3d6d982aL);
    b.class_(false, false, false);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2020121436159318058");
    b.version(2);
    b.associate("field", 0x1c08e9be3d6d982dL).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14433L).optional(false).origin("2020121436159318061").done();
    b.aggregate("domain", 0x1c08e9be3d6d982bL).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe780L).optional(false).ordered(true).multiple(false).origin("2020121436159318059").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIAbstractElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "IAbstractElement", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L);
    b.interface_();
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642982");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIAbstractStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "IAbstractStructure", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.interface_();
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642981");
    b.version(2);
    b.aggregate("elements", 0x7171b68977873e9L).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L).optional(true).ordered(true).multiple(true).origin("510907218761642985").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForISpecialization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "ISpecialization", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873efL);
    b.interface_();
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642991");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Integer", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3dd68bbcL);
    b.class_(false, false, false);
    b.super_("DataDictionaryDsl.structure.Predefined", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2020121436166196156");
    b.version(2);
    b.property("digits", 0x1c08e9be3dd68bbdL).type(PrimitiveTypeId.INTEGER).origin("2020121436166196157").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNonExclusive() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "NonExclusive", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c1bfe4L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873efL);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210572772");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPredefined() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Predefined", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L);
    b.class_(false, true, false);
    b.super_("DataDictionaryDsl.structure.Domain", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe780L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/956416437770774841");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSemantic() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Semantic", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1cba01accce91399L);
    b.class_(false, false, false);
    b.super_("DataDictionaryDsl.structure.Domain", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe780L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2069968820413993881");
    b.version(2);
    b.property("constraint", 0x1c08e9be3d7321a5L).type(PrimitiveTypeId.STRING).origin("2020121436159680933").done();
    b.aggregate("predefined", 0x1c08e9be3d74e92eL).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L).optional(false).ordered(true).multiple(false).origin("2020121436159797550").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Set", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14455L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210541141");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructureDefinition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "StructureDefinition", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff46L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210457926");
    b.version(2);
    b.aggregate("structure", 0x73ede05be9c17ae9L).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L).optional(false).ordered(true).multiple(false).origin("8353579569210555113").done();
    b.aggregate("fieldDefinitions", 0x1c08e9be3d6f6444L).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3d6d982aL).optional(true).ordered(true).multiple(true).origin("2020121436159435844").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Text", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x1c08e9be3de4c133L);
    b.class_(false, false, false);
    b.super_("DataDictionaryDsl.structure.Predefined", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0xd45dfaeceabe939L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/2020121436167127347");
    b.version(2);
    return b.create();
  }
}
