package DataDictionaryDsl.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import DataDictionaryDsl.behavior.Predefined__BehaviorDescriptor;

public class Predefined_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(Predefined__BehaviorDescriptor.getDomainSignature_id1qCH0nUngwF.invoke(ctx.getPrimaryInput()));
  }
}
